language: node_js
node_js:
    - "5"
script:
    - "echo done"
deploy:
    - provider: s3
      access_key_id: $S3_ID
      secret_access_key: $S3_SECRET
      bucket: gallery-content.dataskeptic.com
      endpoint: gallery-content.dataskeptic.com.s3-website-ap-southeast-2.amazonaws.com
      region: ap-southeast-2
      skip_cleanup: true
      on:
          branch: master
