language: node_js

node_js:
    - stable

cache:
  directories:
  - node_modules

before_script:
    - "npm install --prod"

script:
    - "npm run prod"

deploy:
    - provider: s3
      access_key_id: $S3_ID
      secret_access_key: $S3_SECRET
      bucket: gallery-content.dataskeptic.com
      endpoint: gallery-content.dataskeptic.com.s3-website-ap-southeast-2.amazonaws.com
      region: ap-southeast-2
      skip_cleanup: false
      on:
          branch: master
    - provider: s3
      access_key_id: $S3_ID_PROD
      secret_access_key: $S3_SECRET_PROD
      bucket: gallery.openhouseproject.co
      endpoint: http://gallery.openhouseproject.co.s3-website-us-east-1.amazonaws.com/
      skip_cleanup: true
      acl: public_read
      on:
          branch: master
    - provider: s3
      access_key_id: $S3_ID_PROD
      secret_access_key: $S3_SECRET_PROD
      bucket: gallery-dev.openhouseproject.co
      endpoint: http://gallery-dev.openhouseproject.co.s3-website-us-east-1.amazonaws.com/
      skip_cleanup: true
      acl: public_read
      on:
          branch: dev

notifications:
  email:
    recipients:
      - kyle@dataskeptic.com
    on_success: always
    on_failure: always
